import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '../components/providers'
import Navbar from '@/components/navbar'
import Main from '@/components/Main'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'newco',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <Main>
            {children}
          </Main>
        </Providers>
      </body>
    </html>
  )
}
